//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatsArayuz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLRoles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLRoles()
        {
            this.TBLAdminData = new HashSet<TBLAdminData>();
        }
    
        public int Id { get; set; }
        public string Roles { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLAdminData> TBLAdminData { get; set; }
        public virtual TBLUserRoleMappings TBLUserRoleMappings { get; set; }
    }
}
