//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatsArayuz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLVdsListe
    {
        public int Id { get; set; }
        public string SirketAdı { get; set; }
        public string VdsIp { get; set; }
        public string VdsKullanıcıAdı { get; set; }
        public string VdsPw { get; set; }
        public Nullable<int> RemoteDeskId { get; set; }
        public string AnyDesk { get; set; }
        public string AnydeskPw { get; set; }
        public string Notes { get; set; }
        public string TeamViewer { get; set; }
        public string TeamViewerPw { get; set; }
        public string SplashTop { get; set; }
        public string SplashTopPw { get; set; }
        public Nullable<int> SirketTurId { get; set; }
    
        public virtual TBLEkle TBLEkle { get; set; }
        public virtual TBLSirketTur TBLSirketTur { get; set; }
    }
}
