//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatsArayuz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLVdsListe
    {
        public int Id { get; set; }
        public string SirketAdı { get; set; }
        public string VdsIp { get; set; }
        public string VdsKullanıcıAdı { get; set; }
        public string VdsPw { get; set; }
        public Nullable<int> RemoteDeskId { get; set; }
        public string RemoteDeskAd { get; set; }
        public string RemoteDeskPw { get; set; }
        public string Notes { get; set; }
    
        public virtual TBLRemoteDT TBLRemoteDT { get; set; }
    }
}
