//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgiListeleme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCustomerVdsList
    {
        public int Id { get; set; }
        public string Sirketİsmi { get; set; }
        public string Vdsİp { get; set; }
        public string VdsName { get; set; }
        public string VdsPassword { get; set; }
        public string AnyDesk { get; set; }
        public string AnyDeskPw { get; set; }
        public string TeamViewer { get; set; }
        public string TeamViewerPw { get; set; }
        public string Notes { get; set; }
        public string SplashTop { get; set; }
        public string SplashTopPw { get; set; }
        public Nullable<int> RemoteDeskId { get; set; }
    
        public virtual TBLEkle TBLEkle { get; set; }
    }
}
