//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgiListeleme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCustomerVdsList
    {
        public int Id { get; set; }
        public string Sirketİsmi { get; set; }
        public string Vdsİp { get; set; }
        public string VdsName { get; set; }
        public string VdsPassword { get; set; }
        public Nullable<int> RemoteDesktopId { get; set; }
    
        public virtual TBLRemoteDesktop TBLRemoteDesktop { get; set; }
    }
}
