//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgiListeleme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEkle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLEkle()
        {
            this.TBLCustomerVdsList = new HashSet<TBLCustomerVdsList>();
        }
    
        public int Id { get; set; }
        public string RemoteDesktopApp { get; set; }
        public Nullable<bool> sil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCustomerVdsList> TBLCustomerVdsList { get; set; }
    }
}
